# Generated by Django 3.0.7 on 2020-06-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200608_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['data']},
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['data', 'horario']},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['horario']},
        ),
        migrations.AddField(
            model_name='horario',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
    ]
