# Generated by Django 3.0.7 on 2020-06-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200609_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='passado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='passado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
