# Generated by Django 3.0.7 on 2020-06-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200609_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='passado',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='passado',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='reservado',
        ),
        migrations.AddField(
            model_name='agenda',
            name='valida',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='valido',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
